import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';
import ts from 'typescript';

const planner = readFileSync(new URL('../components/StudyPlanner.tsx', import.meta.url), 'utf8');
const shell = readFileSync(new URL('../components/study-planner/LearnerShell.tsx', import.meta.url), 'utf8');
const jsx = (type, props, key) => ({ type, props: props || {}, key });
function compile(source, bindings = {}) {
  const exports = {};
  vm.runInNewContext(ts.transpileModule(source, { compilerOptions: {
    module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX,
  } }).outputText, { exports, ...bindings, require(name) {
    if (name === 'react/jsx-runtime') return { jsx, jsxs: jsx, Fragment: 'fragment' };
    if (name === 'next/image') return { __esModule: true, default: 'Image' };
    if (name === 'next/link') return { __esModule: true, default: 'Link' };
    throw new Error(`Unexpected presentation dependency: ${name}`);
  } });
  return exports;
}
function block(source, start, end) {
  const a = source.indexOf(start), b = source.indexOf(end, a);
  assert.ok(a >= 0 && b > a, `Missing ordered boundary: ${start}`);
  return source.slice(a, b);
}
function expand(node) {
  if (Array.isArray(node)) return node.map(expand);
  if (!node || typeof node !== 'object') return node;
  if (typeof node.type === 'function') return expand(node.type(node.props));
  return { ...node, props: { ...node.props, children: expand(node.props.children) } };
}
function all(node, predicate) {
  if (Array.isArray(node)) return node.flatMap(n => all(n, predicate));
  if (!node || typeof node !== 'object') return [];
  return [...(predicate(node) ? [node] : []), ...all(node.props?.children, predicate)];
}
function digest(node) {
  function normalize(x) {
    if (typeof x === 'function') return '[callback]';
    if (Array.isArray(x)) return x.filter(v => v !== null && v !== undefined && v !== false).map(normalize);
    if (!x || typeof x !== 'object') return x;
    return Object.fromEntries(Object.keys(x).sort().filter(k => x[k] !== undefined).map(k => [k, normalize(x[k])]));
  }
  return createHash('sha256').update(JSON.stringify(normalize(expand(node)))).digest('hex');
}
const components = compile(shell);
const noop = () => {};
const nav = compile(block(planner, 'const learnerNavItems:', 'function createHomeRailItems(').replace('const learnerNavItems:', 'export const learnerNavItems:')).learnerNavItems;
const railItems = compile('export '+block(planner, 'function createHomeRailItems(', 'const CreatorAlgorithmDiagnostics')).createHomeRailItems({ label: 'Creator Studio', href: '/creator' });
const libraries = [{id:'one',slug:'nursing',name:'Nursing'},{id:'two',slug:'science',name:'Science'}];
function header(role, mode, overrides = {}) {
  const descriptors = block(planner, '  const classPrefix: LearnerHeaderPrefix =', '  function descendantNodeIds(');
  const prefix = mode === 'study' ? 'study-v2' : 'home-v2';
  const expressions = planner.split('\n').filter(line => line.trim().startsWith(`<LearnerHeader classPrefix="${prefix}"`));
  assert.equal(expressions.length, 1, 'Exercise the actual mounted header expression');
  return compile('export function renderHeader(){'+descriptors+'return '+expressions[0].trim()+';}', {
    ...components, role, mode, learnerNavItems:nav, email:'fixture@example.invalid', isSaving:false,
    handleHomeClick:noop, handleCreatorClick:noop, openStudyMode:noop, handleLogout:noop, ...overrides,
  }).renderHeader();
}
function rail(overrides = {}) {
  return components.HomeRail({
    items: railItems.map(item => item.href ? {
      kind: 'link', label:item.label, icon:item.icon, href:item.href,
      className:`home-v2-rail-card${item.label === 'Creator Studio' ? ' home-v2-rail-card-primary' : ''}`,
      onClick:item.href.startsWith('/creator') ? (overrides.handleCreatorClick ?? noop) : undefined,
    } : {
      kind:'button', label:item.label, icon:item.icon, className:'home-v2-rail-card',
      onClick:item.label === 'Stats' ? () => (overrides.openStatsTab ?? noop)('progress') : undefined,
    }), onLogout:overrides.handleLogout ?? noop,
  });
}
function switcher(role, availableLibraries, currentSlug, standalone=false) {
  return compile('export '+block(planner, 'function renderLibrarySubjectSwitcher(', "if (homeBootstrapView === 'loading')"), {
    ...components, role, availableLibraries,
  }).renderLibrarySubjectSwitcher(currentSlug, standalone);
}
function fallback(variant, overrides={}) {
  return components.PlannerFallback({ variant, skeletonKeys:railItems.map(x=>x.label), errorText:'Fixture error',
    onRetry:noop, librarySwitcher:switcher('admin',libraries,null,true), showNoActiveLibraries:true,
    message:'Fixture deck error', ...overrides });
}
// Frozen rendered boundary hashes from ed203414, before extraction; not regenerated by the tests.
const baseline = {
  "header:null:dashboard": "ece2c6a23877e626984a9ea3a230981821406db1d6f3b7285390511baa24fb03",
  "header:null:stats": "ece2c6a23877e626984a9ea3a230981821406db1d6f3b7285390511baa24fb03",
  "header:null:study": "a2e77328d00588b8ceb0a2231ad25b93e222fc6f7a22cd3c8f9428dca5f65f18",
  "header:learner:dashboard": "ece2c6a23877e626984a9ea3a230981821406db1d6f3b7285390511baa24fb03",
  "header:learner:stats": "ece2c6a23877e626984a9ea3a230981821406db1d6f3b7285390511baa24fb03",
  "header:learner:study": "a2e77328d00588b8ceb0a2231ad25b93e222fc6f7a22cd3c8f9428dca5f65f18",
  "header:editor:dashboard": "ece2c6a23877e626984a9ea3a230981821406db1d6f3b7285390511baa24fb03",
  "header:editor:stats": "f635e7b4157b8a5c2197488bec790822558272b4ae2ce3754dc6c88566bfd13a",
  "header:editor:study": "f34f61f08ad2130e3f1c6ce2145086b2895ece751a1beeba43fae7ebb7efdd3b",
  "header:admin:dashboard": "1dc72b337a4ddf3f29dd5eb4f019a4f71f144e5aae9a51e34613e7a969edd2f1",
  "header:admin:stats": "3e600c3dbe65dc0c3acc4a9ff85b5db92c3690d37802fbe84e5e7d837c8668f2",
  "header:admin:study": "a1a9340d7baa63bbb1eaf27b69e990d49dd5f14962f932c8177faf7b81c8d004",
  "rail": "52a66bc0cbb84a10b9c57decfc5d3a6e4b7d02b979564cb1acc991ae898071e0",
  "switch:null": "b56d90cd14bece84938449d872ebcfffc96b2d85ad05910df1044c49215c9dc2",
  "switch:nursing": "f73548956d3c79ef5a37233927c7bb8ebfeae7649d97976f85b4f7c86894dbe3",
  "fallback:loading": "37ee12f877d767a8e639c6b98462a9dd3ef52bef5a5d1dc0ecc2efd255285981",
  "fallback:error": "17c4a3987fda0e17b3ae3c16aa7b0af1732f7088ac190c68a2f5088411d51682",
  "fallback:no-library": "52a776bb6138520f3c46db6ae76b5f7317b4a98a16c8af8336b6c1e3b1f544eb",
  "fallback:deck-error": "28bd657ecf7430c075b1e8e730af5777025fe778a3bd1e4e5b72a5c290a76e64"
};

for (const role of [null,'learner','editor','admin']) for (const mode of ['dashboard','stats','study']) {
  test(`released header DOM and authority matrix: ${role}/${mode}`,()=>{
    const rendered=header(role,mode), tree=expand(rendered);
    let original=rendered;
    if(mode==='dashboard') {
      assert.equal(rendered.props.items.some(item=>item.label==='Home'),false);
      // Project back only the removed Home action; retain every frozen DOM hash.
      original={...rendered,props:{...rendered.props,items:[{
        label:'Home',icon:'home',className:'home-v2-nav-item',accountChevron:false,
        kind:'link',href:'/',onClick:noop,prefetch:false,
      },...rendered.props.items]}};
    }
    assert.equal(digest(original),baseline[`header:${role}:${mode}`]);
    const links=all(tree,n=>n.type==='Link');
    const expected=mode==='dashboard'?['/']:['/','/'];
    if ((role==='editor'||role==='admin') && mode!=='dashboard') expected.push('/creator/concepts/new');
    if(role==='admin') expected.push('/admin/users');
    assert.deepEqual(links.map(n=>n.props.href),expected);
    assert.equal(all(tree,n=>n.type==='nav')[0].props['aria-label'],'Socrates learner navigation');
    assert.equal(links[0].props.prefetch,false);
    if(mode!=='dashboard')assert.equal(links[1].props.prefetch,false);
  });
}
test('header and rail callbacks dispatch once; Menu remains an enabled button without an action',()=>{
  let home=0,creator=0,stats=0,logout=0;
  const h=expand(header('admin','stats',{handleHomeClick:()=>home++,handleCreatorClick:()=>creator++}));
  const links=all(h,n=>n.type==='Link');links[1].props.onClick({});links[2].props.onClick({});
  assert.equal(home,1);assert.equal(creator,1);
  const r=expand(rail({handleCreatorClick:()=>creator++,openStatsTab:t=>{assert.equal(t,'progress');stats++;},handleLogout:()=>logout++}));
  assert.equal(digest(rail()),baseline.rail);
  const rs=all(r,n=>n.type==='Link'||n.type==='button');
  assert.equal(rs[0].props.href,'/creator');rs[0].props.onClick();rs[1].props.onClick();
  assert.equal(rs[2].props.href,'/account');assert.equal(rs[3].type,'button');assert.equal(rs[3].props.disabled,undefined);assert.equal(rs[3].props.onClick,undefined);
  rs[4].props.onClick();assert.deepEqual([creator,stats,logout],[2,1,1]);
  assert.equal(all(r,n=>n.type==='aside')[0].props['aria-label'],'Deck navigation');
});
test('Library visibility remains upstream; native POST and uncontrolled defaults are unchanged',()=>{
  for(const role of [null,'learner']) assert.equal(switcher(role,libraries,'nursing'),null);
  for(const role of ['editor','admin']) {
    assert.equal(switcher(role,[],null),null);assert.equal(switcher(role,libraries.slice(0,1),'nursing'),null);
    for(const slug of [null,'nursing']) {
      const tree=expand(switcher(role,libraries,slug,!slug));
      assert.equal(digest(tree),baseline[`switch:${slug}`]);
      const form=all(tree,n=>n.type==='form')[0], select=all(tree,n=>n.type==='select')[0];
      assert.equal(form.props.action,'/library/switch');assert.equal(form.props.method,'post');assert.equal(form.props.onSubmit,undefined);
      assert.equal(select.props.name,'library_slug');assert.equal(select.props.defaultValue,'nursing');assert.equal(select.props.value,undefined);
      assert.equal(all(tree,n=>n.type==='input')[0].props.name,'return_to');assert.equal(all(tree,n=>n.type==='input')[0].props.value,'/');
    }
    assert.ok(switcher(role,libraries.slice(0,1),null,true));
  }
});
for(const variant of ['loading','error','no-library','deck-error']) test(`released fallback DOM: ${variant}`,()=>{
  const tree=expand(fallback(variant));assert.equal(digest(tree),baseline[`fallback:${variant}`]);
  if(variant==='loading'){assert.equal(tree.props['aria-live'],'polite');assert.equal(tree.props['aria-label'],'Loading your deck');assert.equal(all(tree,n=>n.type==='aside')[0].props['aria-hidden'],'true');}
  if(variant==='error'){let retried=0;const error=expand(fallback(variant,{onRetry:()=>retried++}));assert.equal(all(error,n=>n.props.role==='alert').length,1);all(error,n=>n.type==='button')[0].props.onClick();assert.equal(retried,1);}
  if(variant==='deck-error')assert.equal(tree.type,'div');
});
test('rendering owns no effects, auth, RPCs or navigation; parent retains providers and actions',()=>{
  assert.doesNotMatch(shell,/\b(?:useEffect|useState|useRouter|usePathname|supabase|window|fetch|async)\b/);
  let calls=0;const action=()=>calls++;
  expand(header('admin','study',{handleHomeClick:action,handleCreatorClick:action,openStudyMode:action,handleLogout:action}));
  expand(rail({handleCreatorClick:action,openStatsTab:action,handleLogout:action}));expand(fallback('error',{onRetry:action}));assert.equal(calls,0);
  assert.equal((planner.match(/<HeaderSessionProvider email=\{email\} role=\{role\}>/g)||[]).length,3);
  assert.doesNotMatch(shell,/HeaderSessionProvider|<Header\s/);
  assert.match(planner,/finally \{\s*await supabase\.auth\.signOut\(\);\s*window\.location\.href = '\/login'/);
  assert.match(planner,/fetch\('\/library\/clear', \{ method: 'POST' \}\)/);
  const order=["if (homeBootstrapView === 'loading')","if (homeBootstrapView === 'error')","if (!activeLibrary?.id)","if (!deck)","if (mode === 'study')"];
  let position=planner.indexOf('function renderLibrarySubjectSwitcher(');for(const marker of order){const next=planner.indexOf(marker,position);assert.ok(next>position);position=next;}
  assert.match(planner,/mode !== 'stats'/);assert.match(planner,/home-v2-shell-stats/);assert.match(planner,/className="home-v2-workspace"/);
});

test('ref-owning Study callback remains deferred through the declarative header representation',()=>{
  let opened=0;
  const callback=()=>{opened++;};
  const tree=expand(header('admin','study',{learnerNavItems:[{icon:'study',label:'Study'}],openStudyMode:callback}));
  assert.equal(opened,0);
  const button=all(tree,n=>n.type==='button')[0];
  assert.equal(button.props.onClick,callback);
  button.props.onClick();assert.equal(opened,1);
  assert.doesNotMatch(planner,/function renderLearnerHeader|items\.push\(/);
  assert.equal((planner.match(/<LearnerHeader classPrefix=/g)||[]).length,2);
  assert.ok(planner.includes(`<LearnerHeader classPrefix="home-v2" brandHref="/" onHomeClick={handleHomeClick} items={mode === 'dashboard' ? items.filter(item => item.label !== 'Home') : items} />`));
  assert.doesNotMatch(planner, /<SocratesShell variant="header"/);
  assert.match(planner, /<LearnerHeader classPrefix="study-v2"/);
});
